version: 0.0
os: linux

files:
  - source: app.jar
    destination: /myapplication

hooks:
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ec2-user